version: '2'
services:
  taisan-app:
    image: taisan
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATA_MONGODB_URI=mongodb://taisan-mongodb:27017'
      - SPRING_DATA_MONGODB_DATABASE=taisan
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  taisan-mongodb-node:
    build:
      context: src\main\docker
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  taisan-mongodb-config:
    image: 'mongo:4.0.13'
    container_name: taisan-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
  taisan-mongodb:
    image: 'mongo:4.0.13'
    command: mongos --configdb taisan-mongodb-config
